# Generated by Django 5.1.1 on 2024-11-20 19:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fundit', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subscription',
            old_name='expiration_date',
            new_name='fecha_expiracion',
        ),
        migrations.RenameField(
            model_name='subscription',
            old_name='credit_card_number',
            new_name='numero_tarjeta_credito',
        ),
        migrations.RenameField(
            model_name='subscription',
            old_name='subscription_tier',
            new_name='tipo_suscripcion',
        ),
    ]
