# Generated by Django 5.1.1 on 2024-11-20 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fundit', '0002_rename_expiration_date_subscription_fecha_expiracion_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subscription',
            old_name='cvv',
            new_name='CVV',
        ),
        migrations.RenameField(
            model_name='subscription',
            old_name='interested_ods',
            new_name='ODS_de_interés',
        ),
        migrations.RenameField(
            model_name='subscription',
            old_name='fecha_expiracion',
            new_name='fecha_de_expiración',
        ),
        migrations.RenameField(
            model_name='subscription',
            old_name='numero_tarjeta_credito',
            new_name='número_de_tarjeta_de_crédito',
        ),
        migrations.RenameField(
            model_name='subscription',
            old_name='tipo_suscripcion',
            new_name='tipo_de_suscripción',
        ),
        migrations.RemoveField(
            model_name='ods',
            name='name',
        ),
        migrations.AddField(
            model_name='ods',
            name='nombre',
            field=models.CharField(blank=True, choices=[('1', '1. Fin de la pobreza.'), ('2', '2. Hambre cero.'), ('3', '3. Salud y bienestar.'), ('4', '4. Educación de calidad.'), ('5', '5. Igualdad de género.'), ('6', '6. Agua limpia y saneamiento.'), ('7', '7. Energía asequible y no contaminante.'), ('8', '8. Trabajo decente y crecimiento económico.'), ('9', '9. Industria, innovación e infraestructura.'), ('10', '10. Reducción de las desigualdades.'), ('11', '11. Ciudades y comunidades sostenibles.'), ('12', '12. Producción y consumo responsables.'), ('13', '13. Acción por el clima.'), ('14', '14. Vida submarina.'), ('15', '15. Vida de ecosistemas terrestres'), ('16', '16. Paz, justicia e instituciones sólidas'), ('17', '17. Alianzas para lograr objetivos')], max_length=2),
        ),
    ]
