# Generated by Django 5.1.1 on 2024-11-20 19:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fundit', '0004_alter_subscription_ods_de_interés'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subscription',
            name='ODS_de_interés',
        ),
        migrations.DeleteModel(
            name='ODS',
        ),
    ]
