# Generated by Django 5.1.1 on 2024-11-21 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fundit', '0005_remove_subscription_ods_de_interés_delete_ods'),
    ]

    operations = [
        migrations.CreateModel(
            name='ODS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clave', models.CharField(max_length=50, unique=True)),
                ('nombre', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='CausaSocial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_causa', models.CharField(max_length=255, verbose_name='Nombre de la Causa')),
                ('ong', models.CharField(max_length=255, verbose_name='Nombre de la ONG')),
                ('descripcion', models.TextField(verbose_name='Descripción de la Causa')),
                ('monto_meta', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Monto Meta (CLP)')),
                ('ods_relacionados', models.ManyToManyField(related_name='causas', to='fundit.ods', verbose_name='ODS Relacionados')),
            ],
        ),
    ]
